version: '2.3'

services:
  # Port service
  port-service:
    build: microservices/port-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - MANAGEMENT_HEALTH_RABBIT_ENABLED=false
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=true
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCECOUNT=2
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCEINDEX=0
    depends_on:
      - kafka
      - mongodb

  port-edgeservice:
    build: microservices/port-edgeservice
    mem_limit: 350m
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - MANAGEMENT_HEALTH_RABBIT_ENABLED=false
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_OUTPUT-RESOURCES_PRODUCER_PARTITION-KEY-EXPRESSION=payload.key
      - SPRING_CLOUD_STREAM_BINDINGS_OUTPUT-RESOURCES_PRODUCER_PARTITION-COUNT=2
#      - SERVER_SSL_KEY_STORE=file:/keystore/edge-test.p12
#      - SERVER_SSL_KEY_STORE_PASSWORD=testtest
#    volumes:
#      - $PWD/keystore:/keystore
    depends_on:
      - kafka
      - port-service

  mongodb:
    image: mongo:latest
    mem_limit: 350m
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 20s
      timeout: 5s
      retries: 10

  # Messaging Servie
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    mem_limit: 350m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.6
    mem_limit: 350m
    restart: always
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper